#!/bin/bash

#init
RUNIT_VERSION="version 0.1"

PROC_FILE="Procfile"
ENV_FILE=".env"
DEFAULT_PORT="8080"
DATE_FORMAT='+%Y-%m-%d|%H:%M:%S'

#ERROR
OPTIND_ERROR=10
PROCFILE_NOT_FOUND=4041
PROCFILE_CANOT_READ=5021

ENVFILE_NOT_FOUND=4042
ENVFILE_CANOT_READ=5022

PORT_ERROR=301


# Color Print
HIGHLIGHT='\033[1m'
F_BLACK='\033[30;47m'
B_BLACK='\033[40m'
F_RED='\033[31m'
B_RED='\033[41m'
F_GREEN='\033[32m'
B_GREEN='\033[42m'
F_YELLOW='\033[33m'
B_YELLOW='\033[43m'
F_BLUE='\033[34m'
B_BLUE='\033[44m'
F_MAGENTA='\033[35m'
B_MAGENTA='\033[45m'
F_CYAN='\033[36m'
B_CYAN='\033[46m'
F_WHITE='\033[37m'
B_WHITE='\033[47m'
RESET='\033[0m'

function usage() {
    echo "Usage: runit [-c] [-f procfile|Procfile] [-e envfile|.env]"
    echo "Runit Version: $RUNIT_VERSION"
}



function readprocfile(){
    while read line;do
        :
    done < $PROC_FILE
}


#参数处理校验
function verify() {
    while getopts "cf:e:h" opts;
    do
        case $opts in
            c)
                echo "option:c";;
            f)
                echo "option:f, value $OPTARG"
                if [ -e "$OPTARG" ];then
                    PROC_FILE=$OPTARG;
                else
                    echo "Procfile Not Found"
                    exit $PROCFILE_NOT_FOUND;
                fi;;
            e)
                echo "option:e, value $OPTARG"
                if [ -e "$OPTARG" ];then
                    ENV_FILE=$OPTARG;
                else
                    echo "ENV file Not Found"
                    exit $ENVFILE_NOT_FOUND;
                fi;;
            h)
                usage;
                exit 0;;
            \?)
                usagr;
                exit $OPTIND_ERROR;;
        esac
    done
}

function log() {
    
    #time
    #bash -c "date \"$DATE_FORMAT\""
    #app name & log
    
    local time=`date "+%H:%M:%S"`
    local default_app="A App,but No Name"
    local default_msg="No message passed."
    app=${1:-$default_app}
    message=${2:-$default_msg}
    color=${3:-$F_WHITE}

    #echo -e "$HIGHLIGHT$color$time $app\t| $message $RESET"
    printf "$HIGHLIGHT$color%s %-10s|" $time $app
    echo -e "$message $RESET"
    return
    
}

function run_command() {
    :
}

function  load_env_file() {
    echo "Start Load ENV -> $ENV_FILE"
    if [ -e $ENV_FILE ];then
        source $ENV_FILE
        
        # while read line;do
        #     eval "$line"
        # done < $ENV_FILE
    fi
}

function run_procfile() {
    :
}

function main() {
    verify "$@"
    load_env_file
    log "Runit" "Start in now" $F_BLUE
    log "Windowns" "12312 312 31231" $F_YELLOW

}

main "$@"
